### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by safiyyahmohammed** [ResearchKit/GlucoSuccess#13]
Hello, I'm new to xcode and Researchkit. Can you please tell me if it's possible to connect this project to Firebase? If not, how do you get users' data?

**Comment by tricpony** [comment]
Did you ever resolve this issue?  When adding the firebase cocoa pod to my research kit app Xcode has a meltdown.  Would appreciate if you have a tip.

**Comment by safiyyahmohammed** [comment]
Yeah, after I added firebase to the podfile, I was getting the error "Framework not found GoogleToolboxForMac"
GoogleToolboxForMac is a part of Firebase/Messenger, so I added
pod 'GoogleToolboxForMac/Logger' and updated the podfile

**Comment by safiyyahmohammed** [comment]
I also added pod 'Firebase/Messaging' and updated. Basically if you have errors that say you're missing a dependency, add them to the podfile and see if it works

**Comment by tricpony** [comment]
It is not about dependency for me.  Once I reference Firebase/Core & Firebase/AdMob in my pod file then update I get some error about swift regarding the ResearchKit pod and the remedy is to specify use_framework! (something like that), so after I do that I get another error, fix it, then another error and so on.  There must be something simple that I am missing.
